const ACCOUNT_TYPES = {
  ASSET: "ASSET",
  LIABILITY: "LIABILITY",
  EQUITY: "EQUITY",
  REVENUE: "REVENUE",
  EXPENSE: "EXPENSE",
};

const JOURNAL_TYPES = {
  GENERAL: "GENERAL",
  SALES: "SALES",
  PURCHASE: "PURCHASE",
  PAYMENT: "PAYMENT",
};

const JOURNAL_STATUS = {
  DRAFT: "DRAFT",
  POSTED: "POSTED",
  CANCELLED: "CANCELLED",
};

const SALE_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  CANCELLED: "CANCELLED",
};

module.exports = {
  ACCOUNT_TYPES,
  JOURNAL_TYPES,
  JOURNAL_STATUS,
  SALE_STATUS,
};
